### PR TITLE
Build includes a no follow robots.txt

### PR DESCRIPTION
**Pull request by katjam**
Trello card: 
https://trello.com/c/eHGo55lf/272-gh-pages-branch-has-a-no-follow-robot-file

## Description

- Adds a type of build which includes a no follow robot
- Uses that build for staging

@neontribe/sea-map

### CODE REVIEW

**Review by Nikomus — DISMISSED** [review]
Makes sense to me! 🤖

**Comment by katjam** [comment]
:grimacing: Apparently does not make sense to Travis. I'll check it out.

**Comment by katjam** [comment]
@Nikomus Please check my new implementation. It will need to merge before fully tested since before_deploy only runs if there is a deploy triggered.

**Review by Nikomus — APPROVED** [review]
Do we know what it didn't like before? This also looks like it _should_ work 🙂

**Comment by katjam** [comment]
Before, it was not getting any feedback from the build command after build so was sat waiting.

**Pull request merged**
