### PR TITLE
Feat/487 add footer copyright

### PR DESCRIPTION
**Pull request by katjam**
Trello card: 
https://trello.com/c/qMIvc7Go/487-footer-copyright-information

## Description

- Add copyright into to footer
- Very light grey
- Fully visible on mobile screens > 400px
- dynamic end year

@neontribe/sea-map

### CODE REVIEW

**Comment by katjam** [comment]
@stuartleech You can see in deploy preview (you have to dismiss the netlify preview banner as it sits under there)
https://deploy-preview-143--sea-map.netlify.app/

Let me know if you want to change anything.

image
image
image

**Comment by stuartleech** [comment]
That looks great to me!

**Comment by harryharrold** [comment]
@stuartleech @katjam Hi both! Happy New year1§ It's occurring to me that this code is still sitting in a Neontribe team repository and there's really no need for it to do so - maybe we could consider moving it elsewhere?

**Comment by katjam** [comment]
@harryharrold @stuartleech Yeah, we've been discussing that with @Nikomus also.

Stuart's going to identify a suitable email address that someone at SEA has access to then we'll set up an org and we migrate the Netlify as well.

Any rush for this on your side?

**Comment by harryharrold** [comment]
@katjam  Yes, he said. :-) No rush, no absolute need to be honest - just tidying.

**Comment by katjam** [comment]
@stuartleech Let's set up a new github organisation for SEA to own.

In the interim, if you approve this pull request, I can get the copyright merged in.

**Review by stuartleech — APPROVED** [review]
This looks great!

**Pull request merged**
